#ci
stages:
  - install
  - validate
  - build
  - deploy

default:
  image: node:22

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

lint:
  stage: validate
  dependencies:
    - install
  script:
    - npm run lint

test:
  stage: validate
  dependencies:
    - install
  script:
    - npm run test

build:
  stage: build
  dependencies:
    - install
  script:
    - npx nx build emotion-diary --base-href /$CI_PROJECT_NAME/
  artifacts:
    paths:
      - dist/apps/emotion-diary/browser/

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mkdir -p public
    - cp -r dist/apps/emotion-diary/browser/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "homework"'
