export const GIGACHAT_AUTH_KEY_VALUE =
  'MDE5ZGY3YjgtMGI1My03NjdkLWJhNWItYzIwYmI5NTZiMzRiOmYwODNmNGRiLTQ3N2UtNDk3YS04NmNmLTBjZDM5MmQ2NGEyZQ==';

export const GIGACHAT_SCOPE_VALUE = 'GIGACHAT_API_PERS';
